'use client';

import { RoamwiseLogo } from './roamwise-logo';
import { useState } from 'react';
import { LandingPromptDialog } from './landing-prompt-dialog';
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Code2, Compass, FileText, MapPin, Menu, Plane, Sparkles, Terminal, Upload } from 'lucide-react';
import { LandingAgentSection, LandingUploadSection } from './landing-sections';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';

const days = [
  { label: 'Friday', date: '9 Apr', items: [{ time: '12:15', title: 'Arrive in Seville', detail: 'A fresh city. A whole weekend ahead.', icon: Plane }, { time: '15:00', title: 'Settle into your stay', detail: 'Drop the bags and find a favourite café.', icon: MapPin }] },
  { label: 'Saturday', date: '10 Apr', items: [{ time: '10:00', title: 'Explore Plaza de España', detail: 'historic centre · 1 hour 30 minutes · Free', icon: MapPin }, { time: '13:00', title: 'A slow afternoon in the city', detail: 'Leave a little space for the unexpected.', icon: Sparkles }] },
  { label: 'Sunday', date: '11 Apr', items: [{ time: '09:30', title: 'Find a different view', detail: 'A morning walk and a well-earned coffee.', icon: Compass }, { time: '14:00', title: 'Make the day your own', detail: 'Ask your agent for a few more ideas.', icon: Sparkles }] },
];

export default function LandingPage() {
  const [day, setDay] = useState(1);
  return <div className="min-h-screen bg-white text-[#080d18]">
    <div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12">
      <header className="flex h-20 items-center justify-between gap-4 border-b border-[#e8eaed]">
        <a href="/" aria-label="Roamwise homepage" className="inline-flex shrink-0 items-center gap-2.5 rounded-md text-xl font-semibold tracking-[-.045em] outline-none focus-visible:ring-2 focus-visible:ring-[#89909a]">
          <RoamwiseLogo />roamwise<span className="-ml-2 text-[#89909a]">.</span>
        </a>
        <nav aria-label="Main navigation" className="hidden items-center gap-1 md:flex">
          {[['How it works', '#workflow'], ['For agents', '#agents'], ['Upload a trip', '#try-it']].map(([label, href]) => <Button key={href} render={<a href={href} />} variant="ghost" className="h-9 rounded-md px-3 text-[13px] text-[#626b76] hover:bg-[#f4f5f7] hover:text-[#080d18]">{label}</Button>)}
        </nav>
        <div className="flex items-center gap-2">
          <Button render={<a href="/planner/" />} className="h-9 gap-2 rounded-md bg-[#080d18] px-3.5 text-[13px] text-white shadow-sm hover:bg-[#252c38]">Open planner<ArrowUpRight className="size-3.5" /></Button>
          <div className="md:hidden"><DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" size="icon" aria-label="Open navigation menu" className="size-9 rounded-md border-[#e3e5e9] bg-white" />}><Menu className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={10} className="w-56 rounded-xl bg-white p-1.5 text-[#080d18] shadow-lg">
            {[['How it works', '#workflow'], ['For agents', '#agents'], ['Upload a trip', '#try-it']].map(([label, href]) => <DropdownMenuItem key={href} render={<a href={href} />} className="cursor-pointer rounded-md px-3 py-2.5 focus:bg-[#f4f5f7]">{label}</DropdownMenuItem>)}
          </DropdownMenuContent></DropdownMenu></div>
        </div>
      </header>
      <main>
        <section className="grid items-center gap-7 pb-10 pt-16 md:grid-cols-[1.3fr_1fr] md:gap-14 lg:pb-14 lg:pt-28">
          <h1 className="text-[48px] font-semibold leading-[1.02] tracking-[-.055em] sm:text-[68px] lg:text-[86px] xl:text-[94px]">Trip plans <em className="font-normal" style={{fontFamily:'Georgia, serif'}}>built</em> for<br className="hidden xl:block" /> your next <em className="font-normal" style={{fontFamily:'Georgia, serif'}}>adventure.</em></h1>
          <div className="md:pl-6"><p className="max-w-lg text-lg leading-relaxed tracking-[-.02em] text-[#525b68] lg:text-[23px]">Plan with your favourite AI agent. Bring every flight, stay, and day together in one clear, visual trip.</p><div className="mt-7 flex flex-wrap gap-3 lg:mt-9"><Button render={<a href="#try-it" />} className="h-12 rounded-lg bg-[#080d18] px-6 text-white"><ArrowUpRight className="size-4" />Upload a trip</Button><LandingPromptDialog kind="agent" hero /></div></div>
        </section>
        <div className="flex flex-wrap items-center justify-between gap-x-8 gap-y-5 pb-10 text-[#555e6a] lg:pb-12"><p className="max-w-48 text-sm leading-6 lg:text-base">A companion for the<br />agents you already use:</p><div className="flex items-center gap-2 text-lg font-semibold"><Terminal className="size-5" />Codex</div><div className="flex items-center gap-2 text-lg font-semibold"><Sparkles className="size-5" />Claude Code</div><div className="flex items-center gap-2 text-lg font-semibold"><Code2 className="size-5" />Cursor</div><div className="flex items-center gap-2 text-lg font-semibold"><FileText className="size-5" />Any YAML-capable assistant</div></div>
        <section id="showcase" aria-label="Interactive example trip preview" className="relative isolate overflow-hidden bg-[#c5d2d1] px-4 pb-0 pt-12 sm:px-10 sm:pt-20 lg:px-24 lg:pt-24">
          <svg className="pointer-events-none absolute inset-0 -z-10 h-full w-full" viewBox="0 0 1400 900" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="rw-sky" x2="0" y2="1"><stop stopColor="#b9ced7"/><stop offset="1" stopColor="#e8e9d6"/></linearGradient><linearGradient id="rw-hill" x2=".7" y2="1"><stop stopColor="#8b9b71"/><stop offset="1" stopColor="#455e51"/></linearGradient></defs><path fill="url(#rw-sky)" d="M0 0h1400v900H0z"/><path fill="#a9b2a0" d="M0 500Q190 150 500 380T1000 260T1400 320V900H0Z"/><path fill="url(#rw-hill)" d="M0 620Q270 410 600 540T1400 210V900H0Z"/><path fill="#617c62" d="M0 410Q180 620 570 760T1400 640V900H0Z"/><path fill="none" stroke="#dbd4b1" strokeWidth="7" d="M1400 375Q980 415 1100 510T760 740T830 900"/>{Array.from({length:48},(_,i)=><circle key={i} cx={(i*173)%1400} cy={690+(i*43)%210} r={3+(i%4)} fill={['#eac5a2','#e5dbb5','#b4bf91','#f1e3cf'][i%4]} opacity=".8" />)}</svg>
          <div className="mx-auto max-w-[1080px] overflow-hidden rounded-t-xl border border-[#34404a] bg-[#0b1118] text-[#e9edf1] shadow-[0_15px_70px_#0a182c50]">
            <div className="flex h-14 items-center justify-between border-b border-white/10 px-5"><span className="flex items-center gap-2 text-sm font-semibold"><RoamwiseLogo className="size-6" />roamwise.</span><span className="hidden text-[11px] text-[#8e9ca9] sm:block">seville-trip.yaml</span><span className="flex items-center gap-2 text-[10px] text-[#a6bbaa]"><span className="size-1.5 rounded-full bg-[#a6bbaa]" />Example preview</span></div>
            <div className="grid md:grid-cols-[165px_1fr] lg:grid-cols-[180px_1fr]">
              <aside className="hidden border-r border-white/10 p-4 md:block"><p className="mb-5 text-[10px] uppercase tracking-wider text-[#74818f]">Your workspace</p><div className="space-y-2 text-xs"><a href="/planner/" className="flex items-center gap-2 rounded-md bg-[#283441] p-2.5"><CalendarDays className="size-3.5" />Trip plan</a><a href="#try-it" className="flex items-center gap-2 p-2.5 text-[#93a0ad]"><Upload className="size-3.5" />Import YAML</a><a href="/format.md" className="flex items-center gap-2 p-2.5 text-[#93a0ad]"><FileText className="size-3.5" />Trip format</a></div><div className="mt-24 border-t border-white/10 pt-4 text-[10px] leading-5 text-[#74818f]">One trip file.<br />Room for every idea.</div></aside>
              <div className="p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.13em] text-[#96a1ad]">A weekend away</p><h2 className="mt-2 text-2xl font-medium tracking-tight sm:text-3xl">Seville, at your own pace.</h2><p className="mt-2 text-xs text-[#96a1ad]">9–12 April · 2 travellers</p></div><a href="/planner/" className="flex items-center gap-1 rounded-md border border-white/15 px-3 py-2 text-[10px]">Open your trip <ArrowUpRight className="size-3" /></a></div>
                <div className="mt-6 grid grid-cols-3 gap-2 sm:gap-3">{[{label:'The destination',value:'Seville'},{label:'The pace',value:'A long weekend'},{label:'The plan',value:'Yours to shape'}].map(item=><div key={item.label} className="rounded-lg border border-white/10 p-3 sm:p-4"><p className="text-[9px] text-[#8d9aa7] sm:text-[10px]">{item.label}</p><p className="mt-2 text-xs font-medium sm:text-sm">{item.value}</p></div>)}</div>
                <div className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_1fr]"><div className="rounded-lg border border-white/10 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">Your days, together.</h3><CalendarDays className="size-4 text-[#8d9aa7]" /></div><div className="mt-4 flex gap-2" role="group" aria-label="Example itinerary day">{days.map((item,i)=><button key={item.label} onClick={()=>setDay(i)} aria-pressed={day===i} className={`flex-1 rounded-md px-2 py-2 text-[10px] transition-colors ${day===i?'bg-[#d4ddd0] text-[#142119]':'bg-[#18212c] text-[#93a0ad]'}`}>{item.label}<span className="mt-1 block opacity-65">{item.date}</span></button>)}</div><div aria-live="polite" className="mt-3 min-h-44">{days[day].items.map(item=><div key={item.title} className="flex gap-3 border-b border-white/5 py-4"><span className="pt-0.5 text-[10px] text-[#8d9aa7]">{item.time}</span><div><p className="flex items-center gap-2 text-xs"><item.icon className="size-3 text-[#a5b8a4]" />{item.title}</p><p className="mt-2 text-[10px] leading-5 text-[#8d9aa7]">{item.detail}</p></div></div>)}</div></div>
                  <div className="relative min-h-64 overflow-hidden rounded-lg bg-[#d7dfcf]" aria-label="Illustrated map of the example route"><svg viewBox="0 0 360 300" className="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><path d="M0 60L360 210M80 0L160 300M310 0L210 300M0 210L360 90M0 140L360 270" stroke="#f7f6ed" strokeWidth="16"/><path d="M350 0Q260 90 330 170T300 300" fill="none" stroke="#a5c7d0" strokeWidth="26"/><path d="M95 198Q140 100 185 140T270 87" fill="none" stroke="#658076" strokeWidth="3" strokeDasharray="4 4"/>{[[95,198],[185,140],[270,87]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="10" fill="#273e35" stroke="#fff" strokeWidth="3"/><text x={x} y={y+3} textAnchor="middle" fontSize="9" fill="white">{i+1}</text></g>)}</svg><span className="absolute left-3 top-3 rounded-md bg-white/95 px-2 py-1 text-[9px] text-[#354b3b]">Seville · Route illustration</span><div className="absolute bottom-3 left-3 right-3 flex items-center gap-2 rounded-md bg-white/95 p-3 text-[10px] text-[#354b3b]"><MapPin className="size-4" />See how the whole day fits together.</div></div>
                </div><p className="mt-4 text-[9px] text-[#74818f]">Illustrative trip. Click a day to explore the preview.</p>
              </div>
            </div>
          </div>
        </section>
        <section id="workflow" className="py-16 sm:py-24"><div className="grid gap-5 md:grid-cols-2"><h2 className="max-w-lg text-4xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">From a conversation<br />to a <em className="font-normal" style={{fontFamily:'Georgia, serif'}}>real plan.</em></h2><p className="max-w-md self-end text-lg leading-8 text-[#626b76]">Keep the research and back-and-forth with your agent. Roamwise gives the results somewhere to live.</p></div><div className="mt-10 grid border-y border-[#e3e5e9] md:grid-cols-3">{[{title:'Start with an idea.',text:'Tell your assistant where you want to go, when, and what matters. Let it turn the conversation into a Roamwise YAML file.',icon:Sparkles},{title:'Open the bigger picture.',text:'Your agent launches a local preview. Or upload the file here to compare stays, follow the itinerary, and explore the map.',icon:Compass},{title:'Make it your trip.',text:'Refine the options together. Keep the YAML, edit it in the browser, or print the final itinerary to take with you.',icon:Check}].map((item,i)=><article key={item.title} className="border-b border-[#e3e5e9] py-7 last:border-b-0 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><div className="mb-7 flex items-center justify-between"><item.icon className="size-5" /><span className="text-xs text-[#89909a]">0{i+1}</span></div><h3 className="text-xl font-medium">{item.title}</h3><p className="mt-3 text-sm leading-7 text-[#626b76]">{item.text}</p></article>)}</div></section>
        <LandingAgentSection />
        <LandingUploadSection />
      </main>
      <footer className="flex flex-wrap items-center justify-between gap-4 border-t border-[#e3e5e9] py-7 text-xs text-[#626b76]"><a href="/" className="text-lg font-semibold text-[#080d18]">roamwise.</a><span>One portable file. A world of possibilities.</span><a href="/planner/" className="flex items-center gap-1">Open planner <ChevronRight className="size-3" /></a></footer>
    </div>
  </div>;
}
