import { readFile, writeFile } from 'node:fs/promises';
// Unicode ranges preserve international text while browsers download only needed subsets.
for (const [family, faces, target] of [
  [
    'ibm-plex-sans',
    ['400', '400-italic', '500', '600', '700'],
    'app/fonts-ui.css',
  ],
  ['jetbrains-mono', ['400', '400-italic'], 'components/fonts-editor.css'],
]) {
  let css = '/* Generated by scripts/prepare-fonts.mjs; WOFF2 only. */\n';
  for (const face of faces)
    css +=
      (await readFile(`node_modules/@fontsource/${family}/${face}.css`, 'utf8'))
        .replace(/,\s*url\([^)]*\.woff\) format\('woff'\)/g, '')
        .replaceAll('url(./files/', `url(@fontsource/${family}/files/`) + '\n';
  await writeFile(target, css);
}
